<?php

namespace Tests\Feature;

use bjsmasth\Salesforce\Authentication\PasswordAuthentication;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;


class TestSalesForceViaSCIM extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function setUp()
    {

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExample()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
        $options = [
            'grant_type' => 'password',
//            'client_id' => '3MVG9n_HvETGhr3CdmqWTiR77Q_qn8pnO8XeKx1p6Pu7C_5Mz3nCRHDlKUHHReVrmJM1gTjDBhKS.wkrQrPhf',
            'client_id' => '3MVG9n_HvETGhr3CdmqWTiR77Q_O4VhN0OSoNR8Tk0r566BpbsIhUbA_R0o73ZSo4XADN_zlnw7XC04Xjbwn6',
//            'client_secret' => '27530A5695008D8D6B064EE431B8EEA63FE7D8566E8525964286D5B45313C513',
            'client_secret' => '32E70DB52A62FF0E656BE22AC136C1E5F1DE6937EB165D2236921286EFE000C0',
            'username' => 'tuanla-dqb6@force.com',
            'password' => '1qs2wd3efXwFNibvDGKUkuySexV7QyL2R'
        ];

        $salesforce = new PasswordAuthentication($options);
//        $salesforce = new bjsmasth\Salesforce\Authentication\PasswordAuthentication($options);
        $salesforce->authenticate();

        $access_token = $salesforce->getAccessToken();
        $instance_url = $salesforce->getInstanceUrl();

        $query = 'SELECT Id,Name FROM ACCOUNT LIMIT 100';

        $crud = new \bjsmasth\Salesforce\CRUD();
        $crud->query($query);
    }
}
